### ISSUE TITLE
Didn't compiled

### ISSUE THREAD

**Issue by flaviu22** [malikkirchner/connection-pool#1]
I have boost installed on 

`C:/Program Files/boost_1_75_0/boost`

and lib on

`C:/Program Files/boost_1_75_0/libs`

And now I tried:

`mkdir build
`Ok

`cd build`

Ok

`cmake .. -DCMAKE_BUILD_TYPE=Debug|Release|... `
'Release' is not recognized as an internal or external command, operable program or batch file.

`cmake .. -DCMAKE_BUILD_TYPE=Debug`

```
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18363.
CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: unit_test_framework) (found version
  "1.75.0")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.20/Modules/FindBoost.cmake:2344 (find_package_handle_standard_args)
  test/CMakeLists.txt:20 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Project/connection-pool/build/CMakeFiles/CMakeOutput.log".
```

Then, I have edited CMakeLists.txt from test, I put this:

```
SET(CMAKE_INCLUDE_PATH ${CMAKE_INCLUDE_PATH} "C:/Program Files/boost_1_75_0/boost")
SET(CMAKE_LIBRARY_PATH ${CMAKE_LIBRARY_PATH} "C:/Program Files/boost_1_75_0/libs")

FIND_PACKAGE(Boost)
IF (Boost_FOUND)
    INCLUDE_DIRECTORIES(${Boost_INCLUDE_DIR})
    ADD_DEFINITIONS( "-DHAS_BOOST" )
ENDIF()

```
before everything.

I got:

```
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18363.
CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: unit_test_framework) (found version
  "1.75.0")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.20/Modules/FindBoost.cmake:2344 (find_package_handle_standard_args)
  test/CMakeLists.txt:28 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Project/connection-pool/build/CMakeFiles/CMakeOutput.log".

```

What I should do in order to compile your code ?

**Comment by malikkirchner** [comment]
Hi @flaviu22, with `cmake .. -DCMAKE_BUILD_TYPE=Debug|Release|...` I meant, choose one of the [built-in cmake build types](https://cmake.org/cmake/help/v3.20/variable/CMAKE_BUILD_TYPE.html). 

I never tried to make this work on Windows, because I do not own a copy. Nevertheless I think there is no Linux specific code in the repo, maybe I am wrong. I already look for [boost](https://github.com/malikkirchner/connection-pool/blob/a08285af572df13cc73bab4e119410b840bd109f/test/CMakeLists.txt#L20), but you might need to give FindBoost a [hint](https://cmake.org/cmake/help/latest/module/FindBoost.html#hints). Try `-DBOOST_ROOT=C:\Program Files\boost_1_75_0` with your cmake call.

**Comment by flaviu22** [comment]
Hello. "I meant, choose one of" I realize only this morning :) due to my late trial (I was tired). Thanks, I'll try what you said.

**Comment by flaviu22** [comment]
I've added following lines to `CMakeLists.txt` from `test`:

```
set(BOOST_ROOT "C:/Program Files/boost_1_75_0")
set(Boost_DBUG ON)
```
before `find_package(Boost COMPONENTS unit_test_framework REQUIRED)`
and then I called:

`cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_GENERATOR_PLATFORM=x64 .
`
for x64, or

`cmake .. -DCMAKE_BUILD_TYPE=Debug
`
for x86. Now is ok.
