### ISSUE TITLE
Excellent piece of code

### ISSUE THREAD

**Issue by flaviu22** [malikkirchner/connection-pool#2]
I want to ask you something: I saw that you used `std::unique_lock` instead of `std::lock_guard`. 

Example:

```
std::size_t ConnectionPool::size_busy() const
{
	std::unique_lock<std::mutex> lock{ m_connections_mtx };
	return m_connections_busy.size();
}

```
this could be written as:

```
std::size_t ConnectionPool::size_busy() const
{
	std::lock_guard<std::mutex> lock{ m_connections_mtx };
	return m_connections_busy.size();
}

```
Right ?

Is there a reason why you did that ? This is not an issue, and I had not your email address :)

Thank you.

**Comment by malikkirchner** [comment]
Hi @flaviu22,

you are right, std::unique_lock is not the best choice, std::lock_guard or std::scoped_lock (c++17) would be leaner. The intent is to have a RAII lock, no deeper thoughts.
